name: OGG FINAL DESTINATION
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5
title: THE WINGS TO PARADISE
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#162334'
    - '#fcf0e0'
    - '#b6cae2'
    - '#ffdd53'
    - '#6d5759'
  brandStrength: 0.1875
  lightness: 0.125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
