name: OGG FINAL DESTINATION
favicon: null
layout_spectrum: 0.2748778078239411
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfe3e5'
    - '#5893b3'
    - '#ec6267'
    - '#8aaec5'
    - '#f2bec5'
  brandStrength: 0.5842676986940205
  lightness: 0.125
  saturation: 0.3125
  rhythmicContrast: 0.6001414800994098
purpose: []
