name: OGG FINAL DESTINATION
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: THE WINGS TO PARADISE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfe3e5'
    - '#5893b3'
    - '#ec6267'
    - '#8aaec5'
    - '#f2bec5'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.6001414800994098
purpose: []
