title: THE WINGS TO PARADISE
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1875
  brandStrength: 0.5
  rhythmicContrast: 0.5
  brandColors:
    - '#272422'
    - '#ff0000'
    - '#8d80a1'
    - '#aecaad'
    - '#ffffff'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: OGG FINAL DESTINATION
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.25924
layout_spectrum: 0.4808511
