title: THE WINGS TO PARADISE
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.1875
  brandStrength: 1
  rhythmicContrast: 0.5
  brandColors:
    - '#E0DFD0'
    - '#B5AB8F'
    - '#1F1E17'
    - '#2766B4'
    - '#7EC631'
  lightness: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: OGG FINAL DESTINATION
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5297872
layout_spectrum: 1
